### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by ivanchromjak** [PressApps/helpdesk#1]
![gitflow_workflow___atlassian_git_tutorial 4](https://cloud.githubusercontent.com/assets/2057187/8513458/29304fae-236c-11e5-89f0-be2d4ec8bbe8.png)

**Comment by chromjak** [comment]
My test comment

**Comment by chromjak** [comment]
Ar eyou sure?

**Comment by chromjak** [comment]
bdfsgdfsgdsfg

**Comment by chromjak** [comment]
![pressapps-dark](https://cloud.githubusercontent.com/assets/2057187/15627705/98397c04-24ec-11e6-9510-44fa193db2ec.png)
 uiuiui

**Comment by chromjak** [comment]
http://cl.ly/gIn0

fgjgjkgjh

http://cl.ly/gIn0+

**Comment by chromjak** [comment]
![pressapps-dark](http://cl.ly/gIn0+)

**Comment by chromjak** [comment]
![image 2016-05-27 at 10 53 07 am](https://cloud.githubusercontent.com/assets/2057187/15627724/f36db3a6-24ec-11e6-994e-a2c625e78e87.png)

**Comment by chromjak** [comment]
- [ ] r2g3223

- [ ] 32g 23g
